export const Data = [
  { key: "AC", value: "AC", id: "clear" },
  { key: "/", value: "/", id: "divide" },
  { key: "x", value: "*", id: "multiply" },
  { key: "7", value: "7", id: "seven" },
  { key: "8", value: "8", id: "eight" },
  { key: "9", value: "9", id: "nine" },
  { key: "-", value: "-", id: "subtract" },
  { key: "4", value: "4", id: "four" },
  { key: "5", value: "5", id: "five" },
  { key: "6", value: "6", id: "six" },
  { key: "+", value: "+", id: "add" },
  { key: "1", value: "1", id: "one" },
  { key: "2", value: "2", id: "two" },
  { key: "3", value: "3", id: "three" },
  { key: "=", value: "=", id: "equals" },
  { key: "0", value: "0", id: "zero" },
  { key: ".", value: ".", id: "decimal" },
];
