export const Data = [
  { key: "AC", id: "clear" },
  { key: "/", id: "divide" },
  { key: "*", id: "multiply" },
  { key: "7", id: "seven" },
  { key: "8", id: "eight" },
  { key: "9", id: "nine" },
  { key: "-", id: "subtract" },
  { key: "4", id: "four" },
  { key: "5", id: "five" },
  { key: "6", id: "six" },
  { key: "+", id: "add" },
  { key: "1", id: "one" },
  { key: "2", id: "two" },
  { key: "3", id: "three" },
  { key: "=", id: "equals" },
  { key: "0", id: "zero" },
  { key: ".", id: "decimal" },
];
